language: go

go:
  - "1.10.x"

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=.coverprofile ./...
  - $GOPATH/bin/goveralls -service=travis-ci